Hw03 mongodb
vitaliy-nekrasov/nodejs-homework-rest-api pull request #2
Opened 2023-01-27 20:08 UTC by vitaliy-nekrasov

Доброго дня! ДЗ готово.

2023-01-27 21:08 UTC, Eastvarga requested changes
Є зауваження, треба доопрацювати

2023-01-27 21:08 UTC, Eastvarga commented on controllers/contactsController.js
> +  }
дивна логіка якщо контакту немає то його немає а чому саме `Contact with the same name is already in the database!`,??? з чого це випливає? Це погано розбивати логіку по різних функціях - тут розумно написати контакт не знайдено, бо його немає а краще розберіться з тим де цю помилку кидати

2023-01-27 21:08 UTC, Eastvarga commented on controllers/contactsController.js
> +  const updatingContact = await updateStatusContact(
updatedContact - краще писати

2023-01-27 21:08 UTC, Eastvarga commented on controllers/contactsController.js
> +  }
Що за постфактум перевірка - приберіть її - вона не потрібна -все що потрібно стосовно полів вирішує валідація по схемі

2023-01-27 21:08 UTC, Eastvarga commented on controllers/contactsController.js
> +const updateStatusContactController = async (req, res, next) => {
updateStatusContactController що за статус? в повітрі, біжить, чекає? може краще toggleContactFavorite? Дуже важливо щобімена відображали дії що робить функція

2023-01-27 21:08 UTC, Eastvarga commented on controllers/contactsController.js
> +};
res.status(200).json(updatingContact); ераще так без зайвої інформації та вкладеності

2023-01-27 21:08 UTC, Eastvarga commented on db/connection.js
> +  return mongoose.connect(process.env.MONGO_URL, {
Краще виносити усі змінні конфігурації до файлу конфігупацій та потім імпортувати їх де потрібно

2023-01-27 21:08 UTC, Eastvarga commented on middlewares/validationMiddleware.js
> +  }).min(1);
Самі схеми краще винести до окремого файлу схем валідації та імпортувати їх до мідлвару валідації

2023-01-27 21:08 UTC, Eastvarga commented on models/contacts.js
>      return newContact;
чому не повертаєте створений у БД об'єкт? Як фронт дізнається айді нового елементу??? Чи Ви працювали з запитами на фронті, невже Ви не привчились до деякиї простих істин стосовно запитів та відповідей?

2023-01-27 21:08 UTC, Eastvarga commented on models/contacts.js
> +    await updateContactService(contactId, body);
таж сама проблема

2023-01-27 21:08 UTC, Eastvarga commented on models/contacts.js
> +    const updatedContact = await getContactById(contactId);
дивна конфігурація - методи мангуста дозволяють зробити запит з оновленням та поверненням оновленного елементу - будь ласка, приведіть логіку до ладу

2023-01-27 21:08 UTC, Eastvarga commented on services/contactsService.js
> +  return object;
невірно, знов теж питання  - повертатись повинен об'єкт після створення з призначеним айді, чому повертаєте аргумент функції?

2023-01-27 21:08 UTC, Eastvarga commented on services/contactsService.js
> +  });
return Contacts.findByIdAndUpdate(contactId, {
    $set: { name, email, phone },
  }); і немає питань, а так - погана, дуже погана логіка

2023-01-27 21:08 UTC, Eastvarga commented on services/contactsService.js
> +  });
теж саме

2023-01-30 07:38 UTC, vitaliy-nekrasov commented
Доброго дня. Наче все виправив. Якось одразу не зрозумів що методи монгуста повертають оновлені елементи

2023-02-01 16:43 UTC, Eastvarga approved these changes

2023-02-01 16:43 UTC, merged