Hw04 auth
vitaliy-nekrasov/nodejs-homework-rest-api pull request #3
Opened 2023-02-05 13:15 UTC by vitaliy-nekrasov

Добрий день. ДЗ готово.

2023-02-05 15:15 UTC, Eastvarga requested changes
В цілому непогано, але є зауваження

2023-02-05 15:15 UTC, Eastvarga commented on middlewares/usersMiddleware.js
> +    const user = jwt.decode(token, JWT_SECRET);
невірно, декодування не веріфікує токен,зазвичай токен має лімітований час життя, тому використовують метод верифікації а не декодування.

2023-02-05 15:15 UTC, Eastvarga commented on middlewares/usersMiddleware.js
> +    req.token = token;
токен не потрібен у запиті він своє діло зробив на етапі мідлвару аутентифікації

2023-02-05 15:15 UTC, Eastvarga commented on routes/api/users.js
> +router.get("/logout", usersMiddleware, logoutController);
usersMiddleware => authMidlware буде доречніше, бо цей мідлвар частина процесу авторізації\аутентифікації

2023-02-05 15:15 UTC, Eastvarga commented on services/usersService.js
> +      });
Ви впевнені що отримаєте оновленого юзера, а не юзера у стані до оновлення?

2023-02-05 15:15 UTC, Eastvarga commented on services/usersService.js
> +      return { updatedUser, token };
чи чпівпвдвють токени усередині юзера з токеном у полі token ?

2023-02-05 15:15 UTC, Eastvarga commented on services/usersService.js
> +    const user = await User.findById(id, { email: 1, subscription: 1, _id: 0 });
поточного юзера після мідлвару авторизації ви можете вітягти з req.user і не потрібно знову запит у базу робити

2023-02-05 15:57 UTC, vitaliy-nekrasov commented on services/usersService.js
> +      });
так, але як дістати саме оновленого юзера, що не робити щє одін запіт до бд. Чи просто перейменувати на юзер?

2023-02-06 16:59 UTC, Eastvarga commented on services/usersService.js
> +      });
читайте документацью там усе є, заодно навчитесь
User.findOneAndUpdate(user._id, {
        $set: { token }, **{ new: true }**
      });
це пише у підказках до функції

2023-02-06 17:07 UTC, Eastvarga requested changes
Є зауваження.

2023-02-06 17:07 UTC, Eastvarga commented on controllers/usersController.js
> +  console.log(req.user);
консоль тут зайва

2023-02-06 17:07 UTC, Eastvarga commented on services/usersService.js
>      return user;
Невірна логіка, якщо пароль не співпадає з хешем, чому повертаєте юзера, коли повинні повернути помилку авторізації?
Передивіться краще матеріали та лекцію

2023-02-07 07:55 UTC, vitaliy-nekrasov commented on services/usersService.js
>      return user;
Прибрав return юзера, якщо нічого не повернеться помилка авторизації прийде з контроллера

2023-02-07 19:08 UTC, Eastvarga approved these changes

2023-02-07 19:08 UTC, merged